# Generated by Django 4.0.2 on 2022-02-28 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor_Contato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CNPJ', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=7)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=18)),
                ('base', models.CharField(max_length=30)),
                ('data_admissao', models.CharField(max_length=20)),
                ('data_demissao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=80)),
                ('matricula', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=70)),
                ('matricula', models.CharField(max_length=7)),
                ('epis', models.CharField(max_length=70)),
                ('cod', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=70)),
                ('quantidade', models.CharField(max_length=20)),
                ('tamanho', models.CharField(max_length=20)),
                ('dia', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=7)),
                ('nome', models.CharField(max_length=100)),
                ('bota', models.CharField(max_length=4)),
                ('calca', models.CharField(max_length=4)),
                ('camisa', models.CharField(max_length=4)),
                ('jaqueta', models.CharField(max_length=4)),
            ],
        ),
    ]
