# Generated by Django 4.0.2 on 2022-02-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='CNPJ',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='fornecedor_contato',
            old_name='CNPJ',
            new_name='cnpj',
        ),
    ]
