# Generated by Django 4.0.2 on 2022-02-28 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_delete_fornecedor_delete_fornecedor_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
