# Generated by Django 4.0.2 on 2022-02-28 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_funcionarios_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
