# Generated by Django 4.0.2 on 2022-02-28 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_fornecedor_alter_funcionarios_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorContato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
