# Generated by Django 4.0.2 on 2022-02-28 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_fornecedorcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=70)),
                ('matricula', models.CharField(max_length=7)),
                ('epis', models.CharField(max_length=70)),
                ('cod', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=70)),
                ('quantidade', models.CharField(max_length=20)),
                ('tamanho', models.CharField(max_length=20)),
                ('dia', models.CharField(max_length=12)),
            ],
        ),
    ]
